CREATE DATABASE IF NOT EXISTS mvj
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE mvj;

-- Yes i like english comments :) mvj = my very job, just joking, mateus vieites de jesus
-- Tabela de Usuários
CREATE TABLE MVJ_USER (
  MVJ_ID INT AUTO_INCREMENT,
  MVJ_USERNAME VARCHAR(50) NOT NULL UNIQUE,
  MVJ_PASSWORD_HASH VARCHAR(255) NOT NULL,
  MVJ_EMAIL VARCHAR(100) NOT NULL UNIQUE,
  MVJ_ROLE CHAR(1) NOT NULL DEFAULT 'U', -- 'A' for Admin, 'U' for User
  MVJ_ACTIVE BOOLEAN DEFAULT TRUE,
  MVJ_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_user PRIMARY KEY (MVJ_ID),
  INDEX idx_user_email (MVJ_EMAIL)
);

-- Tabela de Equipes
CREATE TABLE MVJ_TEAM (
    MVJ_ID INT AUTO_INCREMENT,
    MVJ_NAME VARCHAR(100) NOT NULL,
    MVJ_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_team PRIMARY KEY (MVJ_ID)
);

-- Tabela Relacional Equipe x Usuário
CREATE TABLE MVJ_TEAM_USER (
    MVJ_ID_USER INT,
    MVJ_ID_TEAM INT,
    MVJ_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MVJ_DELETED BOOLEAN DEFAULT FALSE,
    MVJ_DELETED_AT TIMESTAMP NULL,
    CONSTRAINT pk_team_user PRIMARY KEY(MVJ_ID_USER, MVJ_ID_TEAM),
    CONSTRAINT fk_team_user_user FOREIGN KEY (MVJ_ID_USER) REFERENCES MVJ_USER(MVJ_ID),
    CONSTRAINT fk_team_user_team FOREIGN KEY (MVJ_ID_TEAM) REFERENCES MVJ_TEAM(MVJ_ID)
);

-- Tabela de Tarefas
CREATE TABLE MVJ_TASK (
    MVJ_ID INT AUTO_INCREMENT,
    MVJ_TITLE VARCHAR(200) NOT NULL,
    MVJ_PRIORITY CHAR(1) NOT NULL DEFAULT 'M', -- 'H': high 'M': medium, 'L': low
    MVJ_DESCRIPTION TEXT,
    MVJ_STATUS CHAR(1) NOT NULL DEFAULT 'O', -- 'O': Open, 'I': In Progress, 'C': Closed
    MVJ_ASSIGNED_TO INT,
    MVJ_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_task PRIMARY KEY (MVJ_ID),
    CONSTRAINT fk_task_user FOREIGN KEY (MVJ_ASSIGNED_TO) REFERENCES MVJ_USER(MVJ_ID),
    INDEX idx_task_status (MVJ_STATUS)
);

-- Histórico de Alterações das Tarefas
CREATE TABLE MVJ_TASK_HISTORY (
    MVJ_ID INT AUTO_INCREMENT,
    MVJ_TASK_ID INT NOT NULL,
    MVJ_USER_ID INT NOT NULL,
    MVJ_STATUS CHAR(1) NOT NULL, -- 'O': open, 'S': status changed, 'I': in progress, 'C': closed
    MVJ_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_task_history PRIMARY KEY (MVJ_ID),
    CONSTRAINT fk_history_task FOREIGN KEY (MVJ_TASK_ID) REFERENCES MVJ_TASK(MVJ_ID),
    CONSTRAINT fk_history_user FOREIGN KEY (MVJ_USER_ID) REFERENCES MVJ_USER(MVJ_ID)
);